// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxyF5R1o3Rl2VEMNdsHIlIhfcdxyTO1tI',
    appId: '1:550931047600:web:3b2bc705256172daa78775',
    messagingSenderId: '550931047600',
    projectId: 'fasum-rafaeleh',
    authDomain: 'fasum-rafaeleh.firebaseapp.com',
    storageBucket: 'fasum-rafaeleh.firebasestorage.app',
    measurementId: 'G-BWVHE79TT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3jXlLjVg6eSCrSXKU8Keb5f7CcgsbUa4',
    appId: '1:550931047600:android:55fcc29ef3f03350a78775',
    messagingSenderId: '550931047600',
    projectId: 'fasum-rafaeleh',
    storageBucket: 'fasum-rafaeleh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo9x591BwKUcb9zG2y6zkPymh0jAe08kI',
    appId: '1:550931047600:ios:6074f500560a755aa78775',
    messagingSenderId: '550931047600',
    projectId: 'fasum-rafaeleh',
    storageBucket: 'fasum-rafaeleh.firebasestorage.app',
    iosBundleId: 'com.example.fasumRafaeleh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo9x591BwKUcb9zG2y6zkPymh0jAe08kI',
    appId: '1:550931047600:ios:6074f500560a755aa78775',
    messagingSenderId: '550931047600',
    projectId: 'fasum-rafaeleh',
    storageBucket: 'fasum-rafaeleh.firebasestorage.app',
    iosBundleId: 'com.example.fasumRafaeleh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxyF5R1o3Rl2VEMNdsHIlIhfcdxyTO1tI',
    appId: '1:550931047600:web:eb01b5c881e999d7a78775',
    messagingSenderId: '550931047600',
    projectId: 'fasum-rafaeleh',
    authDomain: 'fasum-rafaeleh.firebaseapp.com',
    storageBucket: 'fasum-rafaeleh.firebasestorage.app',
    measurementId: 'G-VYJ4FMWQ5J',
  );
}
